service: bbot
frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  stackName: bbot
  apiName: bbot
  runtime: go1.x
  memorySize: 128
  stage: dev
  region: eu-west-1
  stackTags:
    project: bbot
  tags:
    project: bbot

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - ssm:GetParameter*
        - ssm:DescribeParameters
      Resource:
        Fn::Join:
          - ":"
          - - "arn:aws:ssm"
            - "Ref" : "AWS::Region"
            - "Ref" : "AWS::AccountId"
            - "parameter/bbot/*"
    - Effect: "Allow"
      Action:
        - sqs:SendMessage
      Resource:
        Fn::GetAtt:
          - messageActionQueue
          - Arn
        

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:

  acceptRequest:
    handler: bin/acceptRequest
    events:
      - http:
          path: endpoint/{type}
          method: post
          request:
            parameters:
              paths:
                type: true
    environment:
      SQS_QUEUE_ACTION:
        Ref: messageActionQueue

  takeAction:
    handler: bin/takeAction
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - messageActionQueue
              - Arn

resources:
  Resources:
    messageActionQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "bbot-messageActionQueue"
        Tags:
          - Key: "project"
            Value: "bbot"
