service: bbot
frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  stackName: bbot
  apiName: bbot
  runtime: go1.x
  memorySize: 128
  stage: dev
  region: eu-west-1
  stackTags:
    project: bbot
  tags:
    project: bbot

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - ssm:GetParameter*
        - ssm:DescribeParameters
      Resource:
        Fn::Join:
          - ":"
          - - "arn:aws:ssm"
            - "Ref" : "AWS::Region"
            - "Ref" : "AWS::AccountId"
            - "parameter/bbot/*"
    - Effect: "Allow"
      Action:
        - sqs:SendMessage
      Resource:
        Fn::GetAtt:
          - flagMessageQueue
          - Arn
    - Effect: "Allow"
      Action:
        - sqs:SendMessage
      Resource:
        Fn::GetAtt:
          - sendMessageQueue
          - Arn
        

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:

  actionHandler:
    handler: bin/actionHandler
    events:
      - http:
          path: endpoint/action
          method: post
    environment:
      SQS_QUEUE_FLAGMESSAGE:
        Ref: flagMessageQueue

  msgFlagger:
    handler: bin/msgFlagger
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - flagMessageQueue
              - Arn
    environment:
      SQS_QUEUE_SENDMESSAGE:
        Ref: sendMessageQueue

resources:
  Resources:
    flagMessageQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "bbot-flagMessageQueue"
        Tags:
          - Key: "project"
            Value: "bbot"
    sendMessageQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "bbot-sendMessageQueue"
        Tags:
          - Key: "project"
            Value: "bbot"
